var manufacturers_array = (function (manufacturers) {
  manufacturers = [
    "--Select Make--",
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Bugatti",
    "Buick",
    "Cadillac",
    "Caterham",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Mazda",
    "Mercedes Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Porsche",
    "Ram Trucks",
    "Rolls Royce",
    "Smart",
    "Subaru",
    "Toyota",
    "Tesla",
    "Volkswagen",
    "Volvo"
  ];
  DynamicElements("manufacturers", manufacturers, "option");
})();

